# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: aomcheer
# "service" is the name of this project. This will also be added to your AWS resource names.
service: portfolio-server

custom:
  wsgi:
    app: src/app.app

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
